# Generated by Django 4.2.6 on 2024-02-02 01:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('revenues', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revenues',
            new_name='NewRevenues',
        ),
    ]
