# Generated by Django 4.2.6 on 2024-02-02 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenues', '0002_rename_revenues_newrevenues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategoriesrevenues',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
