# Generated by Django 4.2.6 on 2024-02-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0003_alter_recipecategoriesrevenues_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategoriesrevenues',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
