# Generated by Django 4.2.6 on 2024-02-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0004_alter_recipecategoriesrevenues_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesubcategoriesrevenues',
            name='subcategory_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
